# Generated by Django 3.2.4 on 2021-07-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_desakelurahan_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
