# Generated by Django 3.2.4 on 2021-07-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_anggota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfi', models.ImageField(upload_to='')),
                ('ktp', models.ImageField(upload_to='')),
                ('diri', models.ImageField(upload_to='')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.anggota')),
            ],
        ),
    ]
