# Generated by Django 3.2.4 on 2021-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0005_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
