# Generated by Django 3.2.4 on 2021-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0006_foto_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='diri',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foto',
            name='ktp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foto',
            name='selfi',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
